### ISSUE TITLE
Upload wheel files to PyPi

### ISSUE THREAD

**Issue by nnarain** [nnarain/gameboycore-python#27]
Investigation. Originally read this wasn't possible that's why I used easy_install. On the other hand, I should look into it again since it is the preferable way to install python packages,

**Comment by corymonroe** [comment]
This appears to be the preferred approach for linux wheels: https://github.com/pypa/manylinux

Might not be much work for you as you seem to have travis setup already.

I just have a source dist for the bindings I created:

https://pypi.org/project/pygameboycore/#files
https://github.com/corymonroe/pygameboycore

**Comment by nnarain** [comment]
Awesome thanks. BTW, I ported this library over to pybind11 to simplify things.
