### ISSUE TITLE
Compilation failure (Python 3.6, Ubuntu 18.04, gcc 7.4.0)

### ISSUE THREAD

**Issue by DashLt** [nnarain/gameboycore-python#44]
Hello! GCC is throwing an error when compiling from source. This is the error it throws:
```
   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LITTLEENDIAN__= -DGAMEBOYCORE_STATIC= -D_CRT_SECURE_NO_WARNINGS= -I/usr/local/include/python3.6 -I/home/[username]/.local/include/python3.6m -Isrc/gameboycore/include -I/usr/include/python3.6m -c src/python/gameboycore_module.cpp -o build/temp.linux-x86_64-3.6/src/python/gameboycore_module.o -Wno-format-security -DVERSION_INFO="0.5.3" -std=c++14 -fvisibility=hidden
    In file included from src/python/gameboycore_module.cpp:9:0:
    src/python/gameboycore_python.h: In member function ‘GameboyCorePython::SpriteList GameboyCorePython::getSpriteCache()’:
    src/python/gameboycore_python.h:87:46: error: could not convert ‘(&((GameboyCorePython*)this)->GameboyCorePython::<anonymous>.gb::GameboyCore::getGPU())->std::unique_ptr<gb::GPU>::operator->()->gb::GPU::getSpriteCache()’ from ‘std::array<gb::Sprite, 40>’ to ‘GameboyCorePython::SpriteList {aka std::vector<gb::Sprite>}’
             return this->getGPU()->getSpriteCache();
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

gameboycore.h is in /usr/local/include/gameboycore if that matters.

**Comment by DashLt** [comment]
This is related to the move to pybind11; the app compiles successfully when reverting to a pre-boost commit

**Comment by DashLt** [comment]
I was able to get it to compile by changing getSpriteCache's return type (?) to std::array<gb::Sprite, 40>, but now I'm SIGSEGVing. In the debugger, I'm getting:
`/home/[username]/gameboycore-python/gameboycore.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2gb11GameboyCore6updateEi`

**Comment by DashLt** [comment]
I had to drop the gameboycore source in src/gameboycore. This was not automatically cloned, and you may want to make this clear in the documentation.

**Comment by nnarain** [comment]
Thank you for reporting the issue! The documentation does indeed need to be updated. Initializing submodules if required before the build.

```
git submodule update --init --recursive
```

**Comment by nnarain** [comment]
Building from source is no longer required as of `0.6.0`
